[build]
  publish = "."
  
[functions]
  directory = "netlify/functions"

[functions."sherlock-search"]
  runtime = "python3.8"

[build.environment]
  # Build-time variables
  NODE_VERSION = "18"

# Environment variables are configured in Netlify Dashboard
# Site Settings > Environment Variables:
# VITE_SUPABASE_URL = https://zsionhetkwaslvounaqo.supabase.co
# VITE_SUPABASE_ANON_KEY = [anon key from Supabase dashboard]

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; connect-src 'self' https://zsionhetkwaslvounaqo.supabase.co; img-src 'self' data:; font-src 'self'"

# PWA caching
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"