[build]
  publish = "."
  
[functions]
  directory = "netlify/functions"

[functions."sherlock-search"]
  runtime = "python3.8"

[build.environment]
  # Supabase
  VITE_SUPABASE_URL = "https://zsionhetkwaslvounaqo.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzaW9uaGV0a3dhc2x2b3VuYXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTgwNTUsImV4cCI6MjA3MTYzNDA1NX0.5DVKWx1-r3lkuUo7UVVnorTSq_HTZz3Gr6J6jbDJ5ig"

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; connect-src 'self' https://zsionhetkwaslvounaqo.supabase.co; img-src 'self' data:; font-src 'self'"

# PWA caching
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"