[build]
  publish = "."
  command = "npm run build"
  
[functions]
  directory = "netlify/functions"
  node_bundler = "esbuild"
  external_node_modules = ["web3", "crypto", "axios", "winston", "opossum", "openai", "helmet", "express-slow-down", "xss", "express-validator", "nodemailer", "twilio", "@supabase/supabase-js"]

[functions."sherlock-search"]
  runtime = "python3.8"

[build.environment]
  NODE_VERSION = "18"
  NPM_FLAGS = "--production"
  VITE_SUPABASE_URL = "https://zsionhetkwaslvounaqo.supabase.co"
  VITE_SUPABASE_ANON_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpzaW9uaGV0a3dhc2x2b3VuYXFvIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTYwNTgwNTUsImV4cCI6MjA3MTYzNDA1NX0.5DVKWx1-r3lkuUo7UVVnorTSq_HTZz3Gr6J6jbDJ5ig"

# ✅ ENVIRONMENT VARIABLES SET - Auto-deploy ready!

# Security headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "strict-origin-when-cross-origin"
    Content-Security-Policy = "default-src 'self'; script-src 'self' 'unsafe-inline' https://cdn.jsdelivr.net; style-src 'self' 'unsafe-inline'; connect-src 'self' https://zsionhetkwaslvounaqo.supabase.co https://api.coingecko.com https://api.etherscan.io https://api.bscscan.com https://api.polygonscan.com https://api.snowtrace.io https://api.arbiscan.io https://mainnet.infura.io https://bsc-dataseed1.binance.org https://polygon-rpc.com https://api.avax.network; img-src 'self' data:; font-src 'self'"

# PWA caching
[[headers]]
  for = "/service-worker.js"
  [headers.values]
    Cache-Control = "no-cache"